Add build system support for using https://github.com/triSYCL/sycl
triSYCL/path_tracer pull request #19
Opened 2021-01-22 16:05 UTC by Ralender

2021-01-22 19:44 UTC, keryell requested changes
It does not work for me:
```<%>- cmake .. -DCMAKE_MODULE_PATH=~/Xilinx/Projects/Khronos/SYCL/triSYCL/cmake 
-- targeting: fpga64_sw_emu
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:23 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
```

2021-01-22 19:44 UTC, keryell commented on CMakeLists.txt
> +set(SYCL_CXX_COMPILER "" CACHE STRING "Path to the SYCL compiler to use of not specified the triSYCL CPU implementation will be used" )
Some errors in the sentence?

2021-01-22 19:44 UTC, keryell commented on CMakeLists.txt
> +set(SYCL_DEVICE_TRIPLE "fpga64_sw_emu" CACHE STRING "Device triple to be used. only used with SYCL_CXX_COMPILER")
```suggestion
# Use Xilinx FPGA software emulation by default
set(SYCL_DEVICE_TRIPLE "fpga64_sw_emu" CACHE STRING "Device triple to be used. Only used with SYCL_CXX_COMPILER")
```

2021-01-22 20:39 UTC, keryell commented
Also you need to update the README to explain how to use the new configuration.

2021-01-25 12:47 UTC, Ralender commented
> Also you need to update the README to explain how to use the new configuration.

at this time it is not yet possible to compile. with this recipe.

2021-01-25 14:59 UTC, merged

2021-01-25 15:00 UTC, keryell commented
Thanks!